[pytest]
# Настройки запуска
addopts = -v --strict-markers --alluredir=allure-results --reruns 2 --reruns-delay 1
testpaths = tests

# Маркеры
markers =
    smoke: основные критические проверки (бизнес-логика)
    regression: полная проверка функционала и UI
    website: тесты основного сайта way2automation
    mainpage: тесты главной страницы
    banking: тесты банковского приложения
    manager: тесты интерфейса менеджера банка (создание/удаление)
    registration: тесты форм регистрации и логина
    transaction: тесты денежных операций
    excel_data: тесты для проверки сбора тестовых данных из excel
    droppable: тесты для проверки drag n drop

python_files = test_*.py *_test.py
python_classes = Test*
python_functions = test_*

log_cli = true
log_cli_level = INFO
log_cli_format = %(asctime)s - %(name)s - %(levelname)s - %(message)s

